### ISSUE TITLE
What was required in the original document ‘standard_regressor_UR10E’？

### ISSUE THREAD

**Issue by cuggx** [shamilmamedov/dynamic_calibration#9]
Hello! Is the file ‘standard_regressor_UR10E’ automatically generated from the toolbox? What would it have looked like in the initial state？Thanks！

**Comment by shamilmamedov** [comment]
Hi! It can be generated by calling  `generate_rb_regressor(path_to_urdf)`. It generates a regressor of dimensions (number of active joints) x (10 times number of actuated links). If your robot is not 6dof, then you need to change `generate_rb_regressor(path_to_urdf)` because some of the dimensions there are hard-coded.

**Comment by cuggx** [comment]
I see. Thank you very much.
